### ISSUE TITLE
Module 'networkx' has no attribute 'multipartite_layout'

### ISSUE THREAD

**Issue by ttshaw1** [Mathics3/mathics-django#18]
I've tried installing Mathics with `pip install git+https://github.com/mathics/Mathics.git` and mathics-django with `pip install git+https://github.com/Mathics3/mathics-django.git`. This resulted in successful installation of Mathics3-2.0.1.dev0
and Mathics-Django-2.0.0. Yet when I try to run `mathicsserver` I get the following error
```
warning: database file /home/$USER/.local/var/mathics/mathics.sqlite not found

Migrating database /home/$USER/.local/var/mathics/mathics.sqlite
Traceback (most recent call last):
  File "/home/$USER/anaconda3/lib/python3.7/site-packages/mathics_django/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/$USER/anaconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/$USER/anaconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/$USER/anaconda3/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/$USER/anaconda3/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/$USER/anaconda3/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/$USER/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/$USER/anaconda3/lib/python3.7/site-packages/mathics_django/web/models.py", line 12, in <module>
    from mathics_django.web.format import format_output
  File "/home/$USER/anaconda3/lib/python3.7/site-packages/mathics_django/web/format.py", line 315, in <module>
    "multipartite": nx.multipartite_layout,
AttributeError: module 'networkx' has no attribute 'multipartite_layout'
error: failed to create database
```

I just overcame [issue 1110](https://github.com/mathics/Mathics/issues/1110), so maybe it's related.

**Comment by rocky** [comment]
It appears that the [networkx](https://pypi.org/project/networkx/)  package is necessary. I added that in 75a9fa .

**Comment by ttshaw1** [comment]
@rocky 
I've tried Mathics-Django versions 2.0.1 and 2.0.2.dev0, with Mathics3 version 2.0.1.dev0 and I'm still getting the same error. I tried to check setup.py to see if the change in 75a9fa propagated but wasn't able to find that file on my drive. Apologies if this is something obvious that I'm not seeing, I don't know much about how installation of packages works.

**Comment by rocky** [comment]
Above it says: 

```
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/$USER/anaconda3/lib/python3.7/site-packages/mathics_django/web/models.py", line 12, in <module>
    from mathics_django.web.format import format_output
  File "/home/$USER/anaconda3/lib/python3.7/site-packages/mathics_django/web/format.py", line 315, in <module>
    "multipartite": nx.multipartite_layout,
AttributeError: module 'networkx' has no attribute 'multipartite_layout'
```

If you are really getting the _same_ error, then this means your `networkx` doesn't have multipartite_layout. It is there in [networkx 2.5](https://networkx.org/documentation/stable/reference/generated/networkx.drawing.layout.multipartite_layout.html?highlight=multipartite_layout#networkx.drawing.layout.multipartite_layout). 

Here is what I see on one of my computers:

```
$ python
Python 3.9.1 (default, Jan 24 2021, 21:42:57) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
rocky's .pythonrc loaded
>>> from networkx import multipartite_layout
>>> 
```

So yes, it is there. 

We are vastly under-resourced. Personally, the little time I have to spend on this, I'd rather work on all of the other problems than trying to understand your setup.  There are other forums like [stackoverflow](https://stackoverflow.com/) for getting help on software that isn't installing properly whether it is a bug in our code or in something in your environment. 

If the development environment isn't working for you, don't use it.  The development environemnt is for developers. 

There is also condaforge setup. Or the [docker image from dockerhub](https://hub.docker.com/r/mathicsorg/mathics).

**Comment by rocky** [comment]
For what it's worth, in 70ae21ba networkx is pegged at at least version 2.5.

**Comment by ttshaw1** [comment]
That solved it. Thank you very much.
