### ISSUE TITLE
Can't install Mathics Django locally

### ISSUE THREAD

**Issue by GarkGarcia** [Mathics3/mathics-django#6]
I haven't used the Dajango interface in while. I cloned the directory and tried to installed it but I get this when I try to run it:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Mathics_Django-1.0.2.dev0-py3.6.egg/mathics_django/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/pablo/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/home/pablo/.local/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/pablo/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/Mathics_Django-1.0.2.dev0-py3.6.egg/mathics_django/urls.py", line 14, in <module>
    url(r'^', include('mathics_django.web.urls')),
  File "/home/pablo/.local/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/Mathics_Django-1.0.2.dev0-py3.6.egg/mathics_django/web/urls.py", line 6, in <module>
    from mathics_django.web.views import (
  File "/usr/local/lib/python3.6/dist-packages/Mathics_Django-1.0.2.dev0-py3.6.egg/mathics_django/web/views.py", line 29, in <module>
    from mathics_django.doc import documentation
ModuleNotFoundError: No module named 'mathics_django.doc'
```

I assume I must have some other installation laying around, which is messing things up, but I'm very confused by Python's package management scheme so I decided to create an issue in here.

**Comment by rocky** [comment]
Here is one way you can see paths: 
```
$ python
Python 3.8.6 (default, Oct 23 2020, 23:13:55) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
rocky's .pythonrc loaded
>>> import mathics_django
>>> mathics_django
<module 'mathics_django' from '/tmp/Mathics3/mathics-django/mathics_django/__init__.py'>
>>> import mathics_django.doc
>>> mathics_django.doc
<module 'mathics_django.doc' from '/tmp/Mathics3/mathics-django/mathics_django/doc/__init__.py'>
```

**Comment by GarkGarcia** [comment]
> Here is one way you can see paths:
> 
> ```
> $ python
> Python 3.8.6 (default, Oct 23 2020, 23:13:55) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> rocky's .pythonrc loaded
> >>> import mathics_django
> >>> mathics_django
> <module 'mathics_django' from '/tmp/Mathics3/mathics-django/mathics_django/__init__.py'>
> >>> import mathics_django.doc
> >>> mathics_django.doc
> <module 'mathics_django.doc' from '/tmp/Mathics3/mathics-django/mathics_django/doc/__init__.py'>
> ```

Ok, this what I see:
```
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mathics_django
>>> mathics_django.doc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mathics_django' has no attribute 'doc'
>>> mathics_django
<module 'mathics_django' from '/usr/local/lib/python3.6/dist-packages/Mathics_Django-1.0.2.dev0-py3.6.egg/mathics_django/__init__.py'>
```

Apparently I'm loading the correct package, but for some reason Python fails to recognize that there is a submodule of `mathics_django` called `doc` (?)

**Comment by GarkGarcia** [comment]
This happens even when I run Python from inside my local copy of the repository:

```
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mathics_django
>>> mathics_django.doc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mathics_django' has no attribute 'doc'
>>> mathics_django
<module 'mathics_django' from '/home/pablo/Documents/mathics-django/mathics_django/__init__.py'>
>>>
```

**Comment by rocky** [comment]
Hmm. Looks like I omitted `mathics_django.doc` as a package. Commit 99eb1452 should address this I at least partially. 

What you want to do though in general in these situations is look `/usr/local/lib/python3.6/dist-packages/Mathics_Django-1.0.2.dev0-py3.6.egg/mathics_django/` `/home/pablo/Documents/mathics-django/mathics_django/`  and 

to see if there is a `doc` directory and whether it contains `doc/__init__.py` (or pyc).

I will guess one or both don't. However these files do appear on master:  https://github.com/Mathics3/mathics-django/tree/master/mathics_django/doc  Maybe you haven't pulled sources in a while or are on a particularly early branch that doesn't have this?

**Comment by GarkGarcia** [comment]
> Hmm. Looks like I omitted `mathics_django.doc` as a package. Commit [99eb145](https://github.com/Mathics3/mathics-django/commit/99eb145296aa1b5731572e61e8efea9082b22b64) should address this, at least partially.
> 
> What you want to do though in general in these situations is look `/usr/local/lib/python3.6/dist-packages/Mathics_Django-1.0.2.dev0-py3.6.egg/mathics_django/` `/home/pablo/Documents/mathics-django/mathics_django/` and
> 
> to see if there is a `doc` directory and whether it contains `doc/__init__.py` (or pyc).

Thanks for the help!
 
> I will guess one or both don't. However these files do appear on master: https://github.com/Mathics3/mathics-django/tree/master/mathics_django/doc Maybe you haven't pulled sources in a while or are on a particularly early branch that doesn't have this?

I actually cloned the repository today...

Ok, https://github.com/Mathics3/mathics-django/commit/99eb145296aa1b5731572e61e8efea9082b22b64 fixed that issue and now `mathicsserver` boots, but there are still missing files:

![Screenshot_2020-12-31 TemplateDoesNotExist at ](https://user-images.githubusercontent.com/37553739/103384507-62a77b00-4b42-11eb-8561-98f4e354c225.png)

I looked at `/usr/local/lib/python3.6/dist-packages/Mathics_Django-1.0.2.dev0-py3.6.egg` and indeed there is no HTML files in there:

```
/usr/local/lib/python3.6/dist-packages/Mathics_Django-1.0.2.dev0-py3.6.egg $ ls **.html
fish: No matches for wildcard “**.html”. See `help expand`.
ls **.html
   ^
```

**Comment by GarkGarcia** [comment]
In [`fish`](https://fishshell.com/) `**.html` matches any file that ends on `.html` in _any_ subdirectory of the current working directory. In other words, there are no HTML files in any subdirectory of `/usr/local/lib/python3.6/dist-packages/Mathics_Django-1.0.2.dev0-py3.6.egg`.

**Comment by rocky** [comment]
I think I got the naming wrong in setup.py using a `-` instead of a `_` which seems to get used when this is converted to an egg. 

See https://github.com/Mathics3/mathics-django/blob/master/setup.py#L128-L129 See if changing this from a `-` to `_` fixes this.  If so make the commit. 

Sorry for the hassle.

**Comment by rocky** [comment]
One thing that's kind of interesting here is that the docker image doesn't have this problem (nor do I have it locally). 

I am guessing that is because they both are running from the source tree.

However it is absolutely true that we do want this to work from install from PyPI.

**Comment by rocky** [comment]
BTW when you do get this running, when you look at the Gallery examples you should see two new combinatorica examples. And the new commands like `Run` should work and `Integrate[f[x,y], {x}]` should have the right kind of `d` although the top of the integral sign sometmes is chopped off.

**Comment by GarkGarcia** [comment]
> _EDIT:_
> I got the naming wrong in setup.py using a `-` instead of a `_` which seems to get used when this is converted to an egg.
> 
> See https://github.com/Mathics3/mathics-django/blob/master/setup.py#L128-L129 ~See if changing this from a `-` to `_` fixes this. If so make the commit~.
>
> All the changes have been made in 7fd06ce and some local testing suggests this works (at least for me).

Thanks for the work! The installation now works flawlessly. 

> Sorry for the hassle.

No worries. I'm sorry I couldn't help you to transfer the code from core to here a while ago. This sort of work is bound to small mistakes like this.

> One thing that's kind of interesting here is that the docker image doesn't have this problem (nor do I have it locally).
> 
> I am guessing that is because they both are running from the source tree.

This puzzeled me too. Indeed, "running from the source tree" is the only explanation I could come with.

> BTW when you do get this running, _assuming Mathics 2.0.0dev_ is installed need to bump the min version in setup.py - if you'd do that this would be aweome) (done in last commit now):
> 
> when you look at the Gallery examples you should see two new combinatorica examples. And the new commands like `Run` should work and `Integrate[f[x,y], {x}]` should have the right kind of `d` although the top of the integral sign sometmes is chopped off.

Yep, the examples and the propper formatting of `Integrate` are all working.  Again, thanks for the work!

**Comment by rocky** [comment]
And most importantly, Django and its dependencies is unbundled from core which means installation and testing are slightly simpler which means they can be expanded (to become as complex again). And then more is broken off, and we repeat.
