### ISSUE TITLE
Pie charts recently stopped working.

### ISSUE THREAD

**Issue by rocky** [Mathics3/mathics-django#81]
Compare: 

```
PieChart[{1, 3, 5, 4}]
```

with what is cached when you load: "04: Displaying Lists"

I looked in the inspector and I see the slices, so I guess it has to do with styling or css.

**Comment by TiagoCavalcanteTrindade** [comment]
@rocky I'm getting the following error:

```wl
System::exception:
Exception raised: 'GraphicsBox' object has no attribute 'boxes_to_svg' Traceback (most recent call last):  File "/home/tiago/mathics-django/mathics_django/web/views.py", line 245, in query result = evaluation.evaluate(expr, timeout=settings.TIMEOUT)  File "/home/tiago/.local/lib/python3.9/site-packages/mathics/core/evaluation.py", line 355, in evaluate result = run_with_timeout_and_stack(evaluate, timeout, self)  File "/home/tiago/.local/lib/python3.9/site-packages/mathics/core/evaluation.py", line 112, in run_with_timeout_and_stack return request()  File "/home/tiago/.local/lib/python3.9/site-packages/mathics/core/evaluation.py", line 348, in evaluate return self.format_output(self.last_eval, format)  File "/home/tiago/mathics-django/mathics_django/web/models.py", line 33, in <lambda> evaluation.format_output = lambda expr, format: format_output(evaluation, expr, format)  File "/home/tiago/mathics-django/mathics_django/web/format.py", line 103, in format_output return eval_boxes(result, result.boxes_to_svg, obj) AttributeError: 'GraphicsBox' object has no attribute 'boxes_to_svg'</lambda>
```

(I forgot to say that my last PR also fix some errors that wasn't showing)

**Comment by rocky** [comment]
I am not seeing this. I'll look into this when I get a chance.

**Comment by rocky** [comment]
Fixed by https://github.com/mathics/Mathics/pull/1421
